### ISSUE TITLE
Error in music assistant `Received error message without cmdId`

### ISSUE THREAD

**Issue by RMHogervorst** [music-assistant/aiosonos#43]
I don't know if this is the right place to ask this question, but I think something is not correct.

here are the logs, I have removed ids. 
```
2024-12-15 14:12:24.095 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/app/venv/lib/python3.12/site-packages/music_assistant/providers/sonos/provider.py", line 259, in play_media
    await sonos_player.client.player.group.play_stream_url(media.uri, None)
  File "/app/venv/lib/python3.12/site-packages/aiosonos/group.py", line 342, in play_stream_url
    await self.client.api.playback_session.load_stream_url(
  File "/app/venv/lib/python3.12/site-packages/aiosonos/api/namespaces/playback_session.py", line 120, in load_stream_url
    await self.api.send_command(
  File "/app/venv/lib/python3.12/site-packages/aiosonos/api/websockets.py", line 93, in send_command
    return await future
           ^^^^^^^^^^^^
aiosonos.exceptions.FailedCommand: Command failed: The sessionId does not match the session on this player.
2024-12-15 14:12:24.830 ERROR (MainThread) [aiosonos.api] Received error message without cmdId: {'namespace': 'playback:1', 'householdId': 'SONOS_HOUSEHOLDID', 'locationId': 'LOCATIONID', 'groupId': 'GROUPID:THINGY', 'name': 'playbackError', 'type': 'playbackError'}

```

**Comment by marcelveldt** [comment]
For support for Music Assistant, ask on the music assistant support channels, not on a library repo.
